name: Continuous Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  #  lint:
  #    name: ğŸ› Code standards
  #    uses: ./.github/workflows/lint.yml

  test:
    name: âœ… Test
    uses: ./.github/workflows/test.yml

  build:
    name: ğŸ—ï¸ Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    name: ğŸš¢ Release
    needs: [ test, build ]
    uses: ./.github/workflows/release.yml
